#Matrix Inverse and Systems of Equations Activity


In [1]:
import numpy as np

# Problem 1: Find the inverse of matrix A = [[3, 4], [2, 5]]

In [2]:
print("Problem 1:")
A1 = np.array([[3, 4],
               [2, 5]])
try:
    A1_inv = np.linalg.inv(A1)
    print("The inverse of matrix A is:")
    print(A1_inv)
    # Verify the result
    print("\nVerification (A * A^-1 should be identity matrix):")
    print(np.round(A1.dot(A1_inv), decimals=10))
except np.linalg.LinAlgError:
    print("Matrix is not invertible")

Problem 1:
The inverse of matrix A is:
[[ 0.71428571 -0.57142857]
 [-0.28571429  0.42857143]]

Verification (A * A^-1 should be identity matrix):
[[ 1.  0.]
 [-0.  1.]]


# Problem 2: Solve system of equations

In [3]:
print("Problem 2:")
# 2x + 3y = 7
# 4x - y = 5
A2 = np.array([[2, 3],
               [4, -1]])
b2 = np.array([7, 5])
solution2 = np.linalg.solve(A2, b2)
print("Solution for x and y:")
print(f"x = {solution2[0]}")
print(f"y = {solution2[1]}")

Problem 2:
Solution for x and y:
x = 1.5714285714285714
y = 1.2857142857142858


# Problem 3: Find inverse of 3x3 matrix

In [4]:
print("Problem 3:")
A3 = np.array([[1, 2, 3],
               [0, 1, 4],
               [5, 6, 0]])
try:
    A3_inv = np.linalg.inv(A3)
    print("The inverse of matrix A is:")
    print(A3_inv)
    # Verify the result
    print("\nVerification (A * A^-1 should be identity matrix):")
    print(np.round(A3.dot(A3_inv), decimals=10))
except np.linalg.LinAlgError:
    print("Matrix is not invertible")

Problem 3:
The inverse of matrix A is:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

Verification (A * A^-1 should be identity matrix):
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


# Problem 4: Solve system of 3 equations

In [5]:
print("Problem 4:")
# x + y + z = 6
# 2x + 5y + z = -4
# 2x + 3y + 8z = 9
A4 = np.array([[1, 1, 1],
               [2, 5, 1],
               [2, 3, 8]])
b4 = np.array([6, -4, 9])
solution4 = np.linalg.solve(A4, b4)
print("Solution for x, y, and z:")
print(f"x = {solution4[0]}")
print(f"y = {solution4[1]}")
print(f"z = {solution4[2]}")

Problem 4:
Solution for x, y, and z:
x = 10.842105263157894
y = -5.2105263157894735
z = 0.3684210526315789


# Problem 5: Solve matrix equation Ax = b

In [6]:
print("Problem 5:")
A5 = np.array([[4, -1, 0],
               [3, 5, 2],
               [-2, 4, 1]])
b5 = np.array([5, 6, 2])
solution5 = np.linalg.solve(A5, b5)
print("Solution for x vector:")
print(solution5)

Problem 5:
Solution for x vector:
[  2.6   5.4 -14.4]


# Bonus Challenge: Function to check invertibility and find inverse

In [7]:
def check_and_inverse(matrix):
    try:
        det = np.linalg.det(matrix)
        if abs(det) < 1e-10:  # Check if determinant is effectively zero
            print("Matrix is not invertible (determinant is zero)")
            return None
        inverse = np.linalg.inv(matrix)
        return inverse
    except np.linalg.LinAlgError:
        print("Matrix is not invertible")
        return None

print("Bonus Challenge - Testing the function:")
test_matrix = np.array([[1, 2], [2, 4]])  # Non-invertible matrix
result = check_and_inverse(test_matrix)
if result is not None:
    print("Inverse exists:")
    print(result)

Bonus Challenge - Testing the function:
Matrix is not invertible (determinant is zero)
